import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  livewireV3Sidebar: [
    {
      type: 'category',
      label: '入门',
      collapsed: false,
      items: [
        'livewire/v3.x/quickstart',
        'livewire/v3.x/installation',
        'livewire/v3.x/upgrading',
      ],
    },
    {
      type: 'category',
      label: '基础',
      collapsed: false,
      items: [
        'livewire/v3.x/components',
        'livewire/v3.x/properties',
        'livewire/v3.x/actions',
        'livewire/v3.x/forms',
        'livewire/v3.x/events',
        'livewire/v3.x/lifecycle-hooks',
        'livewire/v3.x/nesting',
        'livewire/v3.x/testing',
      ],
    },
    {
      type: 'category',
      label: '功能',
      collapsed: true,
      items: [
        'livewire/v3.x/alpine',
        'livewire/v3.x/navigate',
        'livewire/v3.x/lazy',
        'livewire/v3.x/validation',
        'livewire/v3.x/uploads',
        'livewire/v3.x/pagination',
        'livewire/v3.x/url',
        'livewire/v3.x/computed-properties',
        'livewire/v3.x/session-properties',
        'livewire/v3.x/redirecting',
        'livewire/v3.x/downloads',
        'livewire/v3.x/locked',
        'livewire/v3.x/bundling',
        'livewire/v3.x/offline',
        'livewire/v3.x/teleport',
      ],
    },
    {
      type: 'category',
      label: 'HTML 指令',
      collapsed: true,
      items: [
        'livewire/v3.x/wire-click',
        'livewire/v3.x/wire-submit',
        'livewire/v3.x/wire-model',
        'livewire/v3.x/wire-loading',
        'livewire/v3.x/wire-navigate',
        'livewire/v3.x/wire-current',
        'livewire/v3.x/wire-cloak',
        'livewire/v3.x/wire-dirty',
        'livewire/v3.x/wire-confirm',
        'livewire/v3.x/wire-transition',
        'livewire/v3.x/wire-init',
        'livewire/v3.x/wire-poll',
        'livewire/v3.x/wire-offline',
        'livewire/v3.x/wire-ignore',
        'livewire/v3.x/wire-replace',
        'livewire/v3.x/wire-show',
        'livewire/v3.x/wire-stream',
        'livewire/v3.x/wire-text',
      ],
    },
    {
      type: 'category',
      label: '概念',
      collapsed: true,
      items: [
        'livewire/v3.x/morphing',
        'livewire/v3.x/hydration',
        'livewire/v3.x/understanding-nesting',
      ],
    },
    {
      type: 'category',
      label: '高级',
      collapsed: true,
      items: [
        'livewire/v3.x/troubleshooting',
        'livewire/v3.x/security',
        'livewire/v3.x/javascript',
        'livewire/v3.x/synthesizers',
        'livewire/v3.x/contribution-guide',
      ],
    },
    {
      type: 'category',
      label: '包',
      collapsed: true,
      items: [
        'livewire/v3.x/volt',
      ],
    },
  ],
  filamentV4Sidebar: [
    {
      type: 'category',
      label: '介绍',
      collapsed: false,
      items: [
        'filament/v4.x/introduction/overview',
        'filament/v4.x/introduction/installation',
        'filament/v4.x/introduction/ai',
        'filament/v4.x/introduction/optimizing-local-development',
      ],
    },
    {
      type: 'category',
      label: '指南',
      collapsed: true,
      items: [
        'filament/v4.x/getting-started',
      ],
    },
    {
      type: 'category',
      label: '资源',
      collapsed: true,
      items: [
        'filament/v4.x/resources/overview',
        'filament/v4.x/resources/listing-records',
        'filament/v4.x/resources/creating-records',
        'filament/v4.x/resources/editing-records',
        'filament/v4.x/resources/viewing-records',
        'filament/v4.x/resources/deleting-records',
        'filament/v4.x/resources/managing-relationships',
        'filament/v4.x/resources/nesting',
        'filament/v4.x/resources/singular',
        'filament/v4.x/resources/global-search',
        'filament/v4.x/resources/widgets',
        'filament/v4.x/resources/custom-pages',
        'filament/v4.x/resources/code-quality-tips',
      ],
    },
    {
      type: 'category',
      label: '表格',
      collapsed: true,
      items: [
        'filament/v4.x/tables/overview',
        {
          type: 'category',
          label: '列',
          collapsed: true,
          items: [
            'filament/v4.x/tables/columns/overview',
            'filament/v4.x/tables/columns/text',
            'filament/v4.x/tables/columns/icon',
            'filament/v4.x/tables/columns/image',
            'filament/v4.x/tables/columns/color',
            'filament/v4.x/tables/columns/select',
            'filament/v4.x/tables/columns/toggle',
            'filament/v4.x/tables/columns/text-input',
            'filament/v4.x/tables/columns/checkbox',
            'filament/v4.x/tables/columns/custom-columns',
          ],
        },
        {
          type: 'category',
          label: '过滤器',
          collapsed: true,
          items: [
            'filament/v4.x/tables/filters/overview',
            'filament/v4.x/tables/filters/select',
            'filament/v4.x/tables/filters/ternary',
            'filament/v4.x/tables/filters/query-builder',
            'filament/v4.x/tables/filters/custom',
            'filament/v4.x/tables/filters/layout',
          ],
        },
        'filament/v4.x/tables/actions',
        'filament/v4.x/tables/layout',
        'filament/v4.x/tables/summaries',
        'filament/v4.x/tables/grouping',
        'filament/v4.x/tables/empty-state',
        'filament/v4.x/tables/custom-data',
      ],
    },
    {
      type: 'category',
      label: '模式',
      collapsed: true,
      items: [
        'filament/v4.x/schemas/overview',
        'filament/v4.x/schemas/layouts',
        'filament/v4.x/schemas/sections',
        'filament/v4.x/schemas/tabs',
        'filament/v4.x/schemas/wizards',
        'filament/v4.x/schemas/callouts',
        'filament/v4.x/schemas/empty-states',
        'filament/v4.x/schemas/primes',
        'filament/v4.x/schemas/custom-components',
      ],
    },
    {
      type: 'category',
      label: '表单',
      collapsed: true,
      items: [
        'filament/v4.x/forms/overview',
        'filament/v4.x/forms/text-input',
        'filament/v4.x/forms/select',
        'filament/v4.x/forms/checkbox',
        'filament/v4.x/forms/toggle',
        'filament/v4.x/forms/checkbox-list',
        'filament/v4.x/forms/radio',
        'filament/v4.x/forms/date-time-picker',
        'filament/v4.x/forms/file-upload',
        'filament/v4.x/forms/rich-editor',
        'filament/v4.x/forms/markdown-editor',
        'filament/v4.x/forms/repeater',
        'filament/v4.x/forms/builder',
        'filament/v4.x/forms/tags-input',
        'filament/v4.x/forms/textarea',
        'filament/v4.x/forms/key-value',
        'filament/v4.x/forms/color-picker',
        'filament/v4.x/forms/toggle-buttons',
        'filament/v4.x/forms/slider',
        'filament/v4.x/forms/code-editor',
        'filament/v4.x/forms/hidden',
        'filament/v4.x/forms/custom-fields',
        'filament/v4.x/forms/validation',
      ],
    },
    {
      type: 'category',
      label: '信息列表',
      collapsed: true,
      items: [
        'filament/v4.x/infolists/overview',
        'filament/v4.x/infolists/text-entry',
        'filament/v4.x/infolists/icon-entry',
        'filament/v4.x/infolists/image-entry',
        'filament/v4.x/infolists/color-entry',
        'filament/v4.x/infolists/code-entry',
        'filament/v4.x/infolists/key-value-entry',
        'filament/v4.x/infolists/repeatable-entry',
        'filament/v4.x/infolists/custom-entries',
      ],
    },
    {
      type: 'category',
      label: '操作',
      collapsed: true,
      items: [
        'filament/v4.x/actions/overview',
        'filament/v4.x/actions/modals',
        'filament/v4.x/actions/grouping-actions',
        'filament/v4.x/actions/create',
        'filament/v4.x/actions/edit',
        'filament/v4.x/actions/view',
        'filament/v4.x/actions/delete',
        'filament/v4.x/actions/replicate',
        'filament/v4.x/actions/force-delete',
        'filament/v4.x/actions/restore',
        'filament/v4.x/actions/import',
        'filament/v4.x/actions/export',
      ],
    },
    {
      type: 'category',
      label: '通知',
      collapsed: true,
      items: [
        'filament/v4.x/notifications/overview',
        'filament/v4.x/notifications/database-notifications',
        'filament/v4.x/notifications/broadcast-notifications',
      ],
    },
    {
      type: 'category',
      label: '小部件',
      collapsed: true,
      items: [
        'filament/v4.x/widgets/overview',
        'filament/v4.x/widgets/stats-overview',
        'filament/v4.x/widgets/charts',
      ],
    },
    {
      type: 'category',
      label: '配置',
      collapsed: true,
      items: [
        'filament/v4.x/panel-configuration',
      ],
    },
    {
      type: 'category',
      label: '导航',
      collapsed: true,
      items: [
        'filament/v4.x/navigation/overview',
        'filament/v4.x/navigation/custom-pages',
        'filament/v4.x/navigation/user-menu',
        'filament/v4.x/navigation/clusters',
      ],
    },
    {
      type: 'category',
      label: '用户',
      collapsed: true,
      items: [
        'filament/v4.x/users/overview',
        'filament/v4.x/users/multi-factor-authentication',
        'filament/v4.x/users/tenancy',
      ],
    },
    {
      type: 'category',
      label: '样式',
      collapsed: true,
      items: [
        'filament/v4.x/styling/overview',
        'filament/v4.x/styling/css-hooks',
        'filament/v4.x/styling/colors',
        'filament/v4.x/styling/icons',
      ],
    },
    {
      type: 'category',
      label: '高级',
      collapsed: true,
      items: [
        'filament/v4.x/advanced/render-hooks',
        'filament/v4.x/advanced/assets',
        'filament/v4.x/advanced/enums',
        'filament/v4.x/advanced/file-generation',
        'filament/v4.x/advanced/modular-architecture',
        'filament/v4.x/advanced/security',
      ],
    },
    {
      type: 'category',
      label: '测试',
      collapsed: true,
      items: [
        'filament/v4.x/testing/overview',
        'filament/v4.x/testing/testing-resources',
        'filament/v4.x/testing/testing-tables',
        'filament/v4.x/testing/testing-schemas',
        'filament/v4.x/testing/testing-actions',
        'filament/v4.x/testing/testing-notifications',
      ],
    },
    {
      type: 'category',
      label: '插件',
      collapsed: true,
      items: [
        'filament/v4.x/plugins/getting-started',
        'filament/v4.x/plugins/panel-plugins',
        'filament/v4.x/plugins/building-a-panel-plugin',
        'filament/v4.x/plugins/building-a-standalone-plugin',
        'filament/v4.x/plugins/configurable-resources-and-pages',
      ],
    },
    {
      type: 'category',
      label: '组件',
      collapsed: true,
      items: [
        'filament/v4.x/components/overview',
        'filament/v4.x/components/action',
        'filament/v4.x/components/form',
        'filament/v4.x/components/infolist',
        'filament/v4.x/components/notifications',
        'filament/v4.x/components/schema',
        'filament/v4.x/components/table',
        'filament/v4.x/components/widget',
        'filament/v4.x/components/avatar',
        'filament/v4.x/components/badge',
        'filament/v4.x/components/breadcrumbs',
        'filament/v4.x/components/button',
        'filament/v4.x/components/callout',
        'filament/v4.x/components/checkbox',
        'filament/v4.x/components/dropdown',
        'filament/v4.x/components/empty-state',
        'filament/v4.x/components/fieldset',
        'filament/v4.x/components/icon-button',
        'filament/v4.x/components/input-wrapper',
        'filament/v4.x/components/input',
        'filament/v4.x/components/link',
        'filament/v4.x/components/loading-indicator',
        'filament/v4.x/components/modal',
        'filament/v4.x/components/pagination',
        'filament/v4.x/components/section',
        'filament/v4.x/components/select',
        'filament/v4.x/components/tabs',
      ],
    },
    {
      type: 'category',
      label: '部署',
      collapsed: true,
      items: [
        'filament/v4.x/deployment',
      ],
    },
    {
      type: 'category',
      label: '升级',
      collapsed: true,
      items: [
        'filament/v4.x/upgrade-guide',
      ],
    },
  ],
  alpineV3Sidebar: [
    {
      type: 'category',
      label: '入门',
      collapsed: false,
      items: [
        'alpine/v3.x/start-here',
        'alpine/v3.x/upgrade-guide',
      ],
    },
    {
      type: 'category',
      label: '基础',
      collapsed: false,
      items: [
        'alpine/v3.x/essentials/installation',
        'alpine/v3.x/essentials/state',
        'alpine/v3.x/essentials/templating',
        'alpine/v3.x/essentials/events',
        'alpine/v3.x/essentials/lifecycle',
      ],
    },
    {
      type: 'category',
      label: '指令',
      collapsed: true,
      items: [
        'alpine/v3.x/directives/data',
        'alpine/v3.x/directives/init',
        'alpine/v3.x/directives/show',
        'alpine/v3.x/directives/bind',
        'alpine/v3.x/directives/on',
        'alpine/v3.x/directives/text',
        'alpine/v3.x/directives/html',
        'alpine/v3.x/directives/model',
        'alpine/v3.x/directives/modelable',
        'alpine/v3.x/directives/for',
        'alpine/v3.x/directives/transition',
        'alpine/v3.x/directives/effect',
        'alpine/v3.x/directives/ignore',
        'alpine/v3.x/directives/ref',
        'alpine/v3.x/directives/cloak',
        'alpine/v3.x/directives/teleport',
        'alpine/v3.x/directives/if',
        'alpine/v3.x/directives/id',
      ],
    },
    {
      type: 'category',
      label: '魔法属性',
      collapsed: true,
      items: [
        'alpine/v3.x/magics/el',
        'alpine/v3.x/magics/refs',
        'alpine/v3.x/magics/store',
        'alpine/v3.x/magics/watch',
        'alpine/v3.x/magics/dispatch',
        'alpine/v3.x/magics/nextTick',
        'alpine/v3.x/magics/root',
        'alpine/v3.x/magics/data',
        'alpine/v3.x/magics/id',
      ],
    },
    {
      type: 'category',
      label: '全局方法',
      collapsed: true,
      items: [
        'alpine/v3.x/globals/alpine-data',
        'alpine/v3.x/globals/alpine-store',
        'alpine/v3.x/globals/alpine-bind',
      ],
    },
    {
      type: 'category',
      label: '插件',
      collapsed: true,
      items: [
        'alpine/v3.x/plugins/mask',
        'alpine/v3.x/plugins/intersect',
        'alpine/v3.x/plugins/resize',
        'alpine/v3.x/plugins/persist',
        'alpine/v3.x/plugins/focus',
        'alpine/v3.x/plugins/collapse',
        'alpine/v3.x/plugins/anchor',
        'alpine/v3.x/plugins/morph',
        'alpine/v3.x/plugins/sort',
      ],
    },
    {
      type: 'category',
      label: '高级',
      collapsed: true,
      items: [
        'alpine/v3.x/advanced/csp',
        'alpine/v3.x/advanced/reactivity',
        'alpine/v3.x/advanced/extending',
        'alpine/v3.x/advanced/async',
      ],
    },
  ],
  flightV3Sidebar: [
    {
      type: 'category',
      label: '安装',
      collapsed: false,
      items: [
        'flight/v3.x/install/install',
      ],
    },
    {
      type: 'category',
      label: '入门',
      collapsed: false,
      items: [
        'flight/v3.x/learn/learn',
      ],
    },
    {
      type: 'category',
      label: '核心文档',
      collapsed: true,
      items: [
        'flight/v3.x/learn/routing',
        'flight/v3.x/learn/middleware',
        'flight/v3.x/learn/autoloading',
        'flight/v3.x/learn/requests',
        'flight/v3.x/learn/responses',
        'flight/v3.x/learn/templates',
        'flight/v3.x/learn/security',
        'flight/v3.x/learn/configuration',
        'flight/v3.x/learn/events',
        'flight/v3.x/learn/extending',
        'flight/v3.x/learn/filtering',
        'flight/v3.x/learn/dependency_injection_container',
        'flight/v3.x/learn/collections',
        'flight/v3.x/learn/json',
        'flight/v3.x/learn/simple_pdo',
        'flight/v3.x/learn/pdo_wrapper',
        'flight/v3.x/learn/uploaded_file',
        'flight/v3.x/learn/unit_testing',
        'flight/v3.x/learn/ai',
      ],
    },
    {
      type: 'category',
      label: '进阶主题',
      collapsed: true,
      items: [
        'flight/v3.x/learn/why_frameworks',
        'flight/v3.x/learn/migrating_to_v3',
        'flight/v3.x/learn/flight_vs_laravel',
        'flight/v3.x/learn/flight_vs_slim',
        'flight/v3.x/learn/flight_vs_symfony',
        'flight/v3.x/learn/flight_vs_fat_free',
        'flight/v3.x/learn/flight_vs_another_framework',
      ],
    },
    {
      type: 'category',
      label: '测试与 SOLID',
      collapsed: true,
      items: [
        'flight/v3.x/learn/unit_testing_and_solid_principles',
      ],
    },
    {
      type: 'category',
      label: '插件',
      collapsed: true,
      items: [
        'flight/v3.x/awesome-plugins/awesome_plugins',
        'flight/v3.x/awesome-plugins/session',
        'flight/v3.x/awesome-plugins/tracy',
        'flight/v3.x/awesome-plugins/tracy_extensions',
        'flight/v3.x/awesome-plugins/latte',
        'flight/v3.x/awesome-plugins/runway',
        'flight/v3.x/awesome-plugins/active_record',
        'flight/v3.x/awesome-plugins/apm',
        'flight/v3.x/awesome-plugins/async',
        'flight/v3.x/awesome-plugins/easy_query',
        'flight/v3.x/awesome-plugins/ghost_session',
        'flight/v3.x/awesome-plugins/jwt',
        'flight/v3.x/awesome-plugins/mcp',
        'flight/v3.x/awesome-plugins/migrations',
        'flight/v3.x/awesome-plugins/permissions',
        'flight/v3.x/awesome-plugins/php_cookie',
        'flight/v3.x/awesome-plugins/php_encryption',
        'flight/v3.x/awesome-plugins/php_file_cache',
        'flight/v3.x/awesome-plugins/simple_job_queue',
        'flight/v3.x/awesome-plugins/comment_template',
        'flight/v3.x/awesome-plugins/n0nag0n_wordpress',
      ],
    },
    {
      type: 'category',
      label: '指南',
      collapsed: true,
      items: [
        'flight/v3.x/guides/blog',
        'flight/v3.x/guides/unit_testing',
      ],
    },
    {
      type: 'category',
      label: '其他',
      collapsed: true,
      items: [
        'flight/v3.x/about',
        'flight/v3.x/examples',
        'flight/v3.x/guides',
        'flight/v3.x/license',
        'flight/v3.x/media',
      ],
    },
  ],
  marktextV1Sidebar: [
    {
      type: 'category',
      label: '快速开始',
      collapsed: false,
      items: [
        'marktext/v1.x/README',
        'marktext/v1.x/end-user/BASICS',
        'marktext/v1.x/end-user/EDITING',
        'marktext/v1.x/end-user/MARKDOWN_SYNTAX',
        'marktext/v1.x/end-user/SPELLING',
      ],
    },
    {
      type: 'category',
      label: '安装与平台',
      collapsed: false,
      items: [
        'marktext/v1.x/end-user/INSTALLATION',
        'marktext/v1.x/end-user/PORTABLE',
        'marktext/v1.x/end-user/LINUX',
        'marktext/v1.x/end-user/ENVIRONMENT',
        'marktext/v1.x/end-user/APPLICATION_DATA_DIRECTORY',
      ],
    },
    {
      type: 'category',
      label: '使用指南',
      collapsed: true,
      items: [
        'marktext/v1.x/end-user/FAQ',
        'marktext/v1.x/end-user/CLI',
        'marktext/v1.x/end-user/PREFERENCES',
        'marktext/v1.x/end-user/KEYBINDINGS',
        'marktext/v1.x/end-user/KEYBINDINGS_LINUX',
        'marktext/v1.x/end-user/KEYBINDINGS_OSX',
        'marktext/v1.x/end-user/KEYBINDINGS_WINDOWS',
      ],
    },
    {
      type: 'category',
      label: '导出与图片',
      collapsed: true,
      items: [
        'marktext/v1.x/end-user/EXPORT',
        'marktext/v1.x/end-user/EXPORT_THEMES',
        'marktext/v1.x/end-user/IMAGES',
        'marktext/v1.x/end-user/IMAGE_UPLOADER_CONFIGRATION',
      ],
    },
    {
      type: 'category',
      label: '主题',
      collapsed: true,
      items: [
        'marktext/v1.x/end-user/THEMES',
      ],
    },
    {
      type: 'category',
      label: '开发者文档',
      collapsed: true,
      items: [
        'marktext/v1.x/dev/README',
        'marktext/v1.x/dev/ARCHITECTURE',
        'marktext/v1.x/dev/BUILD',
        'marktext/v1.x/dev/DEBUGGING',
        'marktext/v1.x/dev/INTERFACE',
        'marktext/v1.x/dev/IPC',
        'marktext/v1.x/dev/LINUX_DEV',
        'marktext/v1.x/dev/PERFORMANCE',
        'marktext/v1.x/dev/RELEASE',
        'marktext/v1.x/dev/RELEASE_HOTFIX',
        'marktext/v1.x/dev/TYPESCRIPT',
        'marktext/v1.x/dev/CODE_OF_CONDUCT',
      ],
    },
    {
      type: 'category',
      label: '其他',
      collapsed: true,
      items: [
        'marktext/v1.x/CHANGELOG',
      ],
    },
  ],
};

export default sidebars;
