import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  livewireV3Sidebar: [
    {
      type: 'category',
      label: '入门',
      collapsed: false,
      items: [
        'livewire/v3.x/quickstart',
        'livewire/v3.x/installation',
        'livewire/v3.x/upgrading',
      ],
    },
    {
      type: 'category',
      label: '基础',
      collapsed: false,
      items: [
        'livewire/v3.x/components',
        'livewire/v3.x/properties',
        'livewire/v3.x/actions',
        'livewire/v3.x/forms',
        'livewire/v3.x/events',
        'livewire/v3.x/lifecycle-hooks',
        'livewire/v3.x/nesting',
        'livewire/v3.x/testing',
      ],
    },
    {
      type: 'category',
      label: '功能',
      collapsed: true,
      items: [
        'livewire/v3.x/alpine',
        'livewire/v3.x/navigate',
        'livewire/v3.x/lazy',
        'livewire/v3.x/validation',
        'livewire/v3.x/uploads',
        'livewire/v3.x/pagination',
        'livewire/v3.x/url',
        'livewire/v3.x/computed-properties',
        'livewire/v3.x/session-properties',
        'livewire/v3.x/redirecting',
        'livewire/v3.x/downloads',
        'livewire/v3.x/locked',
        'livewire/v3.x/bundling',
        'livewire/v3.x/offline',
        'livewire/v3.x/teleport',
      ],
    },
    {
      type: 'category',
      label: 'HTML 指令',
      collapsed: true,
      items: [
        'livewire/v3.x/wire-click',
        'livewire/v3.x/wire-submit',
        'livewire/v3.x/wire-model',
        'livewire/v3.x/wire-loading',
        'livewire/v3.x/wire-navigate',
        'livewire/v3.x/wire-current',
        'livewire/v3.x/wire-cloak',
        'livewire/v3.x/wire-dirty',
        'livewire/v3.x/wire-confirm',
        'livewire/v3.x/wire-transition',
        'livewire/v3.x/wire-init',
        'livewire/v3.x/wire-poll',
        'livewire/v3.x/wire-offline',
        'livewire/v3.x/wire-ignore',
        'livewire/v3.x/wire-replace',
        'livewire/v3.x/wire-show',
        'livewire/v3.x/wire-stream',
        'livewire/v3.x/wire-text',
      ],
    },
    {
      type: 'category',
      label: '概念',
      collapsed: true,
      items: [
        'livewire/v3.x/morphing',
        'livewire/v3.x/hydration',
        'livewire/v3.x/understanding-nesting',
      ],
    },
    {
      type: 'category',
      label: '高级',
      collapsed: true,
      items: [
        'livewire/v3.x/troubleshooting',
        'livewire/v3.x/security',
        'livewire/v3.x/javascript',
        'livewire/v3.x/synthesizers',
        'livewire/v3.x/contribution-guide',
      ],
    },
    {
      type: 'category',
      label: '包',
      collapsed: true,
      items: [
        'livewire/v3.x/volt',
      ],
    },
  ],
  filamentV4Sidebar: [
    {
      type: 'category',
      label: '介绍',
      collapsed: false,
      items: [
        'filament/v4.x/introduction/overview',
        'filament/v4.x/introduction/installation',
        'filament/v4.x/introduction/ai',
        'filament/v4.x/introduction/optimizing-local-development',
      ],
    },
    {
      type: 'category',
      label: '指南',
      collapsed: true,
      items: [
        'filament/v4.x/getting-started',
      ],
    },
    {
      type: 'category',
      label: '资源',
      collapsed: true,
      items: [
        'filament/v4.x/resources/overview',
        'filament/v4.x/resources/listing-records',
        'filament/v4.x/resources/creating-records',
        'filament/v4.x/resources/editing-records',
        'filament/v4.x/resources/viewing-records',
        'filament/v4.x/resources/deleting-records',
        'filament/v4.x/resources/managing-relationships',
        'filament/v4.x/resources/nesting',
        'filament/v4.x/resources/singular',
        'filament/v4.x/resources/global-search',
        'filament/v4.x/resources/widgets',
        'filament/v4.x/resources/custom-pages',
        'filament/v4.x/resources/code-quality-tips',
      ],
    },
    {
      type: 'category',
      label: '表格',
      collapsed: true,
      items: [
        'filament/v4.x/tables/overview',
        {
          type: 'category',
          label: '列',
          collapsed: true,
          items: [
            'filament/v4.x/tables/columns/overview',
            'filament/v4.x/tables/columns/text',
            'filament/v4.x/tables/columns/icon',
            'filament/v4.x/tables/columns/image',
            'filament/v4.x/tables/columns/color',
            'filament/v4.x/tables/columns/select',
            'filament/v4.x/tables/columns/toggle',
            'filament/v4.x/tables/columns/text-input',
            'filament/v4.x/tables/columns/checkbox',
            'filament/v4.x/tables/columns/custom-columns',
          ],
        },
        {
          type: 'category',
          label: '过滤器',
          collapsed: true,
          items: [
            'filament/v4.x/tables/filters/overview',
            'filament/v4.x/tables/filters/select',
            'filament/v4.x/tables/filters/ternary',
            'filament/v4.x/tables/filters/query-builder',
            'filament/v4.x/tables/filters/custom',
            'filament/v4.x/tables/filters/layout',
          ],
        },
        'filament/v4.x/tables/actions',
        'filament/v4.x/tables/layout',
        'filament/v4.x/tables/summaries',
        'filament/v4.x/tables/grouping',
        'filament/v4.x/tables/empty-state',
        'filament/v4.x/tables/custom-data',
      ],
    },
    {
      type: 'category',
      label: '模式',
      collapsed: true,
      items: [
        'filament/v4.x/schemas/overview',
        'filament/v4.x/schemas/layouts',
        'filament/v4.x/schemas/sections',
        'filament/v4.x/schemas/tabs',
        'filament/v4.x/schemas/wizards',
        'filament/v4.x/schemas/callouts',
        'filament/v4.x/schemas/empty-states',
        'filament/v4.x/schemas/primes',
        'filament/v4.x/schemas/custom-components',
      ],
    },
    {
      type: 'category',
      label: '表单',
      collapsed: true,
      items: [
        'filament/v4.x/forms/overview',
        'filament/v4.x/forms/text-input',
        'filament/v4.x/forms/select',
        'filament/v4.x/forms/checkbox',
        'filament/v4.x/forms/toggle',
        'filament/v4.x/forms/checkbox-list',
        'filament/v4.x/forms/radio',
        'filament/v4.x/forms/date-time-picker',
        'filament/v4.x/forms/file-upload',
        'filament/v4.x/forms/rich-editor',
        'filament/v4.x/forms/markdown-editor',
        'filament/v4.x/forms/repeater',
        'filament/v4.x/forms/builder',
        'filament/v4.x/forms/tags-input',
        'filament/v4.x/forms/textarea',
        'filament/v4.x/forms/key-value',
        'filament/v4.x/forms/color-picker',
        'filament/v4.x/forms/toggle-buttons',
        'filament/v4.x/forms/slider',
        'filament/v4.x/forms/code-editor',
        'filament/v4.x/forms/hidden',
        'filament/v4.x/forms/custom-fields',
        'filament/v4.x/forms/validation',
      ],
    },
    {
      type: 'category',
      label: '信息列表',
      collapsed: true,
      items: [
        'filament/v4.x/infolists/overview',
        'filament/v4.x/infolists/text-entry',
        'filament/v4.x/infolists/icon-entry',
        'filament/v4.x/infolists/image-entry',
        'filament/v4.x/infolists/color-entry',
        'filament/v4.x/infolists/code-entry',
        'filament/v4.x/infolists/key-value-entry',
        'filament/v4.x/infolists/repeatable-entry',
        'filament/v4.x/infolists/custom-entries',
      ],
    },
    {
      type: 'category',
      label: '操作',
      collapsed: true,
      items: [
        'filament/v4.x/actions/overview',
        'filament/v4.x/actions/modals',
        'filament/v4.x/actions/grouping-actions',
        'filament/v4.x/actions/create',
        'filament/v4.x/actions/edit',
        'filament/v4.x/actions/view',
        'filament/v4.x/actions/delete',
        'filament/v4.x/actions/replicate',
        'filament/v4.x/actions/force-delete',
        'filament/v4.x/actions/restore',
        'filament/v4.x/actions/import',
        'filament/v4.x/actions/export',
      ],
    },
    {
      type: 'category',
      label: '通知',
      collapsed: true,
      items: [
        'filament/v4.x/notifications/overview',
        'filament/v4.x/notifications/database-notifications',
        'filament/v4.x/notifications/broadcast-notifications',
      ],
    },
    {
      type: 'category',
      label: '小部件',
      collapsed: true,
      items: [
        'filament/v4.x/widgets/overview',
        'filament/v4.x/widgets/stats-overview',
        'filament/v4.x/widgets/charts',
      ],
    },
    {
      type: 'category',
      label: '配置',
      collapsed: true,
      items: [
        'filament/v4.x/panel-configuration',
      ],
    },
    {
      type: 'category',
      label: '导航',
      collapsed: true,
      items: [
        'filament/v4.x/navigation/overview',
        'filament/v4.x/navigation/custom-pages',
        'filament/v4.x/navigation/user-menu',
        'filament/v4.x/navigation/clusters',
      ],
    },
    {
      type: 'category',
      label: '用户',
      collapsed: true,
      items: [
        'filament/v4.x/users/overview',
        'filament/v4.x/users/multi-factor-authentication',
        'filament/v4.x/users/tenancy',
      ],
    },
    {
      type: 'category',
      label: '样式',
      collapsed: true,
      items: [
        'filament/v4.x/styling/overview',
        'filament/v4.x/styling/css-hooks',
        'filament/v4.x/styling/colors',
        'filament/v4.x/styling/icons',
      ],
    },
    {
      type: 'category',
      label: '高级',
      collapsed: true,
      items: [
        'filament/v4.x/advanced/render-hooks',
        'filament/v4.x/advanced/assets',
        'filament/v4.x/advanced/enums',
        'filament/v4.x/advanced/file-generation',
        'filament/v4.x/advanced/modular-architecture',
        'filament/v4.x/advanced/security',
      ],
    },
    {
      type: 'category',
      label: '测试',
      collapsed: true,
      items: [
        'filament/v4.x/testing/overview',
        'filament/v4.x/testing/testing-resources',
        'filament/v4.x/testing/testing-tables',
        'filament/v4.x/testing/testing-schemas',
        'filament/v4.x/testing/testing-actions',
        'filament/v4.x/testing/testing-notifications',
      ],
    },
    {
      type: 'category',
      label: '插件',
      collapsed: true,
      items: [
        'filament/v4.x/plugins/getting-started',
        'filament/v4.x/plugins/panel-plugins',
        'filament/v4.x/plugins/building-a-panel-plugin',
        'filament/v4.x/plugins/building-a-standalone-plugin',
        'filament/v4.x/plugins/configurable-resources-and-pages',
      ],
    },
    {
      type: 'category',
      label: '组件',
      collapsed: true,
      items: [
        'filament/v4.x/components/overview',
        'filament/v4.x/components/action',
        'filament/v4.x/components/form',
        'filament/v4.x/components/infolist',
        'filament/v4.x/components/notifications',
        'filament/v4.x/components/schema',
        'filament/v4.x/components/table',
        'filament/v4.x/components/widget',
        'filament/v4.x/components/avatar',
        'filament/v4.x/components/badge',
        'filament/v4.x/components/breadcrumbs',
        'filament/v4.x/components/button',
        'filament/v4.x/components/callout',
        'filament/v4.x/components/checkbox',
        'filament/v4.x/components/dropdown',
        'filament/v4.x/components/empty-state',
        'filament/v4.x/components/fieldset',
        'filament/v4.x/components/icon-button',
        'filament/v4.x/components/input-wrapper',
        'filament/v4.x/components/input',
        'filament/v4.x/components/link',
        'filament/v4.x/components/loading-indicator',
        'filament/v4.x/components/modal',
        'filament/v4.x/components/pagination',
        'filament/v4.x/components/section',
        'filament/v4.x/components/select',
        'filament/v4.x/components/tabs',
      ],
    },
    {
      type: 'category',
      label: '部署',
      collapsed: true,
      items: [
        'filament/v4.x/deployment',
      ],
    },
    {
      type: 'category',
      label: '升级',
      collapsed: true,
      items: [
        'filament/v4.x/upgrade-guide',
      ],
    },
  ],
};

export default sidebars;
